context:
  version: "0.46.0"

package:
  name: lux-cli
  version: ${{ version }}

source:
  url: https://github.com/lumen-oss/lux/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 5273d09ad50a810cdae1fd883afd3e9b055c0a21c77c318c29c86e3cd7701399

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
      OPENSSL_NO_VENDOR: ${{ "1" if unix else "" }} # force linking to host's (conda-forge's) OpenSSL libs on Unix
    interpreter: nu
    content:
      - let prefix = $env.LIBRARY_PREFIX? | default $env.PREFIX
      # instruct Apple's `ld64` linker to drop unused OpenSSL symbols and to add correct `@rpath` for xtask
      - if: osx
        then: $env.RUSTFLAGS = $'($env.RUSTFLAGS?) -C link-arg=-Wl,-dead_strip_dylibs -C link-arg=-Wl,-rpath,($prefix)/lib' | str trim
      # build main app and generate license data
      - cd lux-cli
      - if: win
        then: ^cargo auditable install --path=. --root=($prefix) --no-track --locked --bins --no-default-features --features=vendored
        else: ^cargo auditable install --path=. --root=($prefix) --no-track --locked --bins
      - ^cargo-bundle-licenses --format=yaml --output=../THIRDPARTY.yml
      # generate shell completions and manpage
      - if: build_platform == host_platform
        then:
          - ^lx util completion bash | save --force ($prefix)/share/bash-completion/completions/lx
          - ^lx util completion fish | save --force ($prefix)/share/fish/vendor_completions.d/lx.fish
          - ^lx util completion zsh  | save --force ($prefix)/share/zsh/site-functions/_lx
          - ^lx util man       --target-dir=($prefix)/share/man/man1

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - cmake
    - make
    - nushell
    - perl
    - pkg-config
  host:
    - if: unix
      then:
        - gpgme
        - libgit2
        - libgpg-error
        - openssl

tests:
  - script:
      - lx --help
      - lx --version
  - package_contents:
      bin:
        - lx
      files:
        - if: unix and build_platform == host_platform
          then:
            - share/man/man1/lx.1
            - share/man/man1/lux*.1
            - share/bash-completion/completions/lx
            - share/fish/vendor_completions.d/lx.fish
            - share/zsh/site-functions/_lx
        - if: win and build_platform == host_platform
          then:
            - Library/share/man/man1/lx.1
            - Library/share/man/man1/lux*.1
            - Library/share/bash-completion/completions/lx
            - Library/share/fish/vendor_completions.d/lx.fish
            - Library/share/zsh/site-functions/_lx
      strict: true

about:
  summary: A luxurious package manager for Lua
  description: |
    Lux is a modern package manager for Lua. It manages dependencies, build steps,
    lockfiles, Lua versions, and existing LuaRocks projects through a single CLI.
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://lux.lumen-labs.org
  repository: https://github.com/lumen-oss/lux

extra:
  recipe-maintainers:
    - salim-b
